import * as core from "@actions/core";
import * as github from "@actions/github";
import { exec } from "@actions/exec";
import { Agent, CursorAgentError } from "@cursor/sdk";
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

const BUILD_WORKFLOW = ".github/workflows/build.yml";

type Mode = "bootstrap" | "fix" | "auto";

interface ProjectInfo {
  kind: string;
  install: string;
  build: string;
  setup: string;
}

function detectProject(root: string): ProjectInfo {
  if (existsSync(join(root, "package.json"))) {
    if (existsSync(join(root, "pnpm-lock.yaml"))) {
      return {
        kind: "pnpm",
        setup: `      - uses: pnpm/action-setup@v4\n        with:\n          version: 9\n      - uses: actions/setup-node@v4\n        with:\n          node-version: 22\n          cache: pnpm`,
        install: "pnpm install --frozen-lockfile",
        build: "pnpm run build",
      };
    }
    if (existsSync(join(root, "yarn.lock"))) {
      return {
        kind: "yarn",
        setup: `      - uses: actions/setup-node@v4\n        with:\n          node-version: 22\n          cache: yarn`,
        install: "yarn install --frozen-lockfile",
        build: "yarn build",
      };
    }
    return {
      kind: "npm",
      setup: `      - uses: actions/setup-node@v4\n        with:\n          node-version: 22\n          cache: npm`,
      install: "npm ci",
      build: "npm run build",
    };
  }

  if (existsSync(join(root, "go.mod"))) {
    return {
      kind: "go",
      setup: `      - uses: actions/setup-go@v5\n        with:\n          go-version: stable`,
      install: "go mod download",
      build: "go build ./...",
    };
  }

  if (existsSync(join(root, "Cargo.toml"))) {
    return {
      kind: "rust",
      setup: `      - uses: dtolnay/rust-toolchain@stable`,
      install: "cargo fetch",
      build: "cargo build --release",
    };
  }

  return {
    kind: "unknown",
    setup: "",
    install: "true",
    build: "echo 'unsupported project' && exit 1",
  };
}

function generateBuildWorkflow(project: ProjectInfo): string {
  return `name: Build

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
${project.setup ? project.setup + "\n" : ""}      - name: Install
        run: ${project.install}
      - name: Build
        run: ${project.build}
`;
}

async function runAgent(
  cwd: string,
  prompt: string,
  apiKey: string,
): Promise<string> {
  try {
    const result = await Agent.prompt(prompt, {
      apiKey,
      model: { id: "composer-2.5" },
      local: { cwd, settingSources: [] },
    });
    if (result.status === "error") {
      throw new Error(`Agent run failed: ${result.id}`);
    }
    return result.result ?? "";
  } catch (err) {
    if (err instanceof CursorAgentError) {
      throw new Error(`Cursor startup failed: ${err.message}`);
    }
    throw err;
  }
}

async function fetchFailureLogs(token: string, runId: number): Promise<string> {
  const octokit = github.getOctokit(token);
  const { owner, repo } = github.context.repo;
  const jobs = await octokit.rest.actions.listJobsForWorkflowRun({
    owner,
    repo,
    run_id: runId,
  });

  const parts: string[] = [];
  for (const job of jobs.data.jobs) {
    parts.push(`Job ${job.name}: ${job.conclusion}`);
    try {
      const logs = await octokit.rest.actions.downloadJobLogsForWorkflowRun({
        owner,
        repo,
        job_id: job.id,
      });
      const text = typeof logs.data === "string" ? logs.data : "";
      parts.push(text.slice(-6000));
    } catch {
      parts.push("(logs unavailable)");
    }
  }
  return parts.join("\n");
}

async function commitPr(
  cwd: string,
  token: string,
  branch: string,
  title: string,
): Promise<string> {
  await exec("git", ["config", "user.name", "github-actions[bot]"], { cwd });
  await exec(
    "git",
    ["config", "user.email", "41898282+github-actions[bot]@users.noreply.github.com"],
    { cwd },
  );
  await exec("git", ["checkout", "-b", branch], { cwd });
  await exec("git", ["add", "-A"], { cwd });
  await exec("git", ["commit", "-m", title], { cwd });
  await exec("git", ["push", "--force", "origin", branch], { cwd });

  const octokit = github.getOctokit(token);
  const { owner, repo } = github.context.repo;
  const base =
    github.context.payload?.repository?.default_branch ??
    github.context.ref?.replace("refs/heads/", "") ??
    "main";

  const pr = await octokit.rest.pulls.create({
    owner,
    repo,
    title,
    head: branch,
    base,
    body: "Generated by AgentBuild. Please review.",
  });
  return pr.data.html_url;
}

function writeBuildWorkflow(cwd: string, content: string): void {
  const path = join(cwd, BUILD_WORKFLOW);
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content, "utf8");
}

function resolveMode(input: Mode, cwd: string): "bootstrap" | "fix" {
  if (input === "bootstrap" || input === "fix") return input;
  const hasBuild = existsSync(join(cwd, BUILD_WORKFLOW));
  const failed =
    github.context.eventName === "workflow_run" &&
    github.context.payload.workflow_run?.conclusion === "failure";
  if (!hasBuild) return "bootstrap";
  if (failed) return "fix";
  return "bootstrap";
}

async function run(): Promise<void> {
  const mode = resolveMode(
    (core.getInput("mode") || "auto") as Mode,
    process.env.GITHUB_WORKSPACE || ".",
  );
  const cwd = process.env.GITHUB_WORKSPACE || process.cwd();
  const apiKey = process.env.CURSOR_API_KEY || "";
  const token = process.env.GITHUB_TOKEN || "";

  core.info(`mode: ${mode}`);

  if (mode === "bootstrap") {
    const project = detectProject(cwd);
    core.info(`detected: ${project.kind}`);
    const workflow = generateBuildWorkflow(project);
    writeBuildWorkflow(cwd, workflow);

    if (apiKey) {
      await runAgent(
        cwd,
        `Review and improve ${BUILD_WORKFLOW} for this ${project.kind} project. Only edit CI/build files (.github/workflows/*, package.json scripts). Do not modify src/.`,
        apiKey,
      );
    }

    if (token) {
      const url = await commitPr(
        cwd,
        token,
        `agentbuild/bootstrap-${github.context.runId}`,
        "chore(ci): add build workflow",
      );
      core.setOutput("pr-url", url);
    }
    return;
  }

  if (!apiKey) {
    core.setFailed("CURSOR_API_KEY is required for fix mode");
    return;
  }

  const runId = github.context.payload.workflow_run?.id;
  const logs = runId && token ? await fetchFailureLogs(token, runId) : "";

  await runAgent(
    cwd,
    `Fix the CI build failure. Only edit .github/workflows/* and build commands. Do not modify src/ unless absolutely necessary.\n\nLogs:\n${logs}`,
    apiKey,
  );

  if (token) {
    const url = await commitPr(
      cwd,
      token,
      `agentbuild/fix-${github.context.runId}`,
      "fix(ci): repair build workflow",
    );
    core.setOutput("pr-url", url);
  }
}

run().catch((err: unknown) => {
  core.setFailed(err instanceof Error ? err.message : String(err));
});
