import * as core from "@actions/core";
import * as github from "@actions/github";
import { exec } from "@actions/exec";
import { Agent, CursorAgentError, type SDKMessage } from "@cursor/sdk";
import { existsSync } from "node:fs";
import { join } from "node:path";

const BUILD_WORKFLOW = ".github/workflows/build.yml";

type Mode = "bootstrap" | "fix" | "auto";

const BOOTSTRAP_PROMPT = `扫描此仓库并创建 ${BUILD_WORKFLOW}，一个用于安装依赖并构建项目的 GitHub Actions workflow。

分析方法：
- 阅读 README.md / README.*、CONTRIBUTING、文档及任何安装说明
- 检查清单文件与工具链：package.json、lockfile、pyproject.toml、requirements.txt、go.mod、Cargo.toml、pom.xml、build.gradle、Makefile、Dockerfile 等
- 根据项目实际情况推断正确的包管理器、运行时版本及构建/测试命令 — 不要套用固定模板

Workflow 要求：
- name: Build
- 触发条件：推送到 main/master，以及 pull_request
- runs-on：根据项目需求自动选择合适的 runner
- 步骤：checkout、配置工具链、安装依赖、构建（若项目有测试则一并运行）
- 尽量使用官方 GitHub Actions（actions/checkout@v4、actions/setup-node@v4 等）；如有必要可酌情使用第三方 actions

产物上传（必需）：
- 构建成功后，添加使用 actions/upload-artifact@v4 的步骤上传构建产物
- 使用描述性的 artifact 名称（例如仓库名或项目特定名称）
- 上传所有相关构建产物；必要时使用多个路径条目或 glob
- 设置 if-no-files-found: error，以便未产生产物时 workflow 失败

约束：
- 优先编辑 CI/构建相关文件（.github/workflows/*）
- 尽量不要改动源码，除非不改动源码做不到
- 编写完整、可运行的 workflow — 不要使用占位符
- 根据项目配置（构建命令、.gitignore、工具链默认输出等）识别构建产物；PR 不包含这些文件，其他必要修改可一并提交
- 若本地试跑了构建，提交前还原或清理产生的构建产物，勿将其留在工作区`;

const FIX_PROMPT_PREFIX = `修复 CI 构建失败。

要求：
- 优先编辑 CI/构建相关文件（.github/workflows/*）
- 尽量不要改动源码，除非不改动源码做不到
- 保留或添加构建成功后使用 actions/upload-artifact@v4 上传构建产物的步骤
- 根据项目分析确定构建产物路径；设置 if-no-files-found: error
- 根据项目配置（.gitignore、构建命令、工具链默认输出等）识别构建产物；PR 不包含这些文件，其他必要修改可一并提交
- 若本地试跑了构建，提交前还原或清理产生的构建产物，勿将其留在工作区
- 若提供了同一会话内多次失败的日志，请分析历次错误并避免重复已失败的修复方向`;

const BUILD_WORKFLOW_NAME = "Build";
const SESSION_LOG_PER_ATTEMPT = 5000;
const SESSION_LOG_TOTAL = 24000;

type SessionPr = {
  number: number;
  attempt: number;
  branch: string;
};

function sessionBranch(sessionId: number, attempt: number): string {
  return `agentbuild/session-${sessionId}/attempt-${attempt}`;
}

function sessionPrBody(sessionId: number, attempt: number): string {
  return [
    "Generated by AgentBuild. Please review.",
    "",
    `AgentBuild session \`${sessionId}\`, attempt ${attempt}.`,
    `<!-- agentbuild-session:${sessionId} -->`,
    `<!-- agentbuild-attempt:${attempt} -->`,
  ].join("\n");
}

function parseSessionFromBranch(branch: string): number | null {
  const match = branch.match(/^agentbuild\/session-(\d+)\/attempt-\d+$/);
  return match ? Number(match[1]) : null;
}

function parseAttemptFromBranch(branch: string): number | null {
  const match = branch.match(/^agentbuild\/session-\d+\/attempt-(\d+)$/);
  return match ? Number(match[1]) : null;
}

function parseSessionFromPrBody(body: string): number | null {
  const match = body.match(/<!--\s*agentbuild-session:(\d+)\s*-->/);
  return match ? Number(match[1]) : null;
}

function parseAttemptFromPrBody(body: string): number | null {
  const match = body.match(/<!--\s*agentbuild-attempt:(\d+)\s*-->/);
  return match ? Number(match[1]) : null;
}

function truncate(text: string, max = 500): string {
  return text.length <= max ? text : `${text.slice(0, max)}…`;
}

function formatToolArgs(name: string, args: unknown): string {
  if (!args || typeof args !== "object") return "";
  const record = args as Record<string, unknown>;
  if (name === "Shell" && typeof record.command === "string") {
    return record.command;
  }
  if (typeof record.path === "string") return record.path;
  if (typeof record.file_path === "string") return record.file_path;
  if (typeof record.target_file === "string") return record.target_file;
  try {
    return truncate(JSON.stringify(args), 200);
  } catch {
    return "";
  }
}

function streamDelta(seen: string, text: string): { seen: string; delta: string } {
  if (seen && text.startsWith(seen)) {
    return { seen: text, delta: text.slice(seen.length) };
  }
  return { seen: seen + text, delta: text };
}

class AgentStreamLogger {
  private assistantBuf = "";
  private assistantSeen = "";
  private thinkingBuf = "";
  private thinkingSeen = "";
  private loggedTools = new Set<string>();

  private emitCompleteLines(buf: string, prefix: string): string {
    let rest = buf;
    let idx = rest.indexOf("\n");
    while (idx !== -1) {
      const line = rest.slice(0, idx).trimEnd();
      rest = rest.slice(idx + 1);
      if (line) core.info(`${prefix}${line}`);
      idx = rest.indexOf("\n");
    }
    return rest;
  }

  onAssistantText(text: string): void {
    const { seen, delta } = streamDelta(this.assistantSeen, text);
    this.assistantSeen = seen;
    if (!delta) return;
    this.assistantBuf += delta;
    this.assistantBuf = this.emitCompleteLines(this.assistantBuf, "[agent] ");
  }

  onThinking(text: string, durationMs?: number): void {
    const { seen, delta } = streamDelta(this.thinkingSeen, text);
    this.thinkingSeen = seen;
    this.thinkingBuf += delta;
    if (durationMs == null) return;
    const summary = this.thinkingBuf.replace(/\s+/g, " ").trim();
    if (summary) {
      core.info(
        `[agent] thinking (${Math.round(durationMs / 1000)}s): ${truncate(summary, 500)}`,
      );
    }
    this.thinkingBuf = "";
    this.thinkingSeen = "";
  }

  flush(): void {
    const tail = this.assistantBuf.trimEnd();
    if (tail) core.info(`[agent] ${tail}`);
    this.assistantBuf = "";
  }

  log(event: SDKMessage): void {
    switch (event.type) {
      case "system":
        if (event.subtype === "init") {
          const model =
            typeof event.model === "object" && event.model && "id" in event.model
              ? String(event.model.id)
              : "unknown";
          core.info(`[agent] initialized (model=${model})`);
        }
        break;
      case "status":
        core.info(
          `[agent] status: ${event.status}${event.message ? ` — ${event.message}` : ""}`,
        );
        break;
      case "thinking":
        this.onThinking(event.text, event.thinking_duration_ms);
        break;
      case "assistant":
        for (const block of event.message.content) {
          if (block.type === "text") {
            this.onAssistantText(block.text);
          } else if (block.type === "tool_use") {
            const detail = formatToolArgs(block.name, block.input);
            core.info(
              `[agent] tool → ${block.name}${detail ? `: ${truncate(detail, 300)}` : ""}`,
            );
          }
        }
        break;
      case "tool_call": {
        const detail = formatToolArgs(event.name, event.args);
        if (event.status === "running") {
          const key = `${event.call_id}:running`;
          if (this.loggedTools.has(key)) break;
          this.loggedTools.add(key);
          core.info(
            `[agent] ${event.name}…${detail ? ` ${truncate(detail, 300)}` : ""}`,
          );
        } else if (event.status === "completed") {
          core.info(`[agent] ${event.name} ✓`);
        } else {
          core.info(`[agent] ${event.name} ✗`);
        }
        break;
      }
      case "task":
        if (event.text?.trim()) {
          core.info(
            `[agent] task: ${truncate(event.text.replace(/\s+/g, " ").trim(), 300)}`,
          );
        }
        break;
    }
  }
}

async function validateSetup(
  mode: "bootstrap" | "fix",
  cwd: string,
  apiKey: string,
  token: string,
): Promise<void> {
  if (!apiKey) throw new Error("CURSOR_API_KEY is not set");
  if (!token) throw new Error("GITHUB_TOKEN is not set");

  core.info("validating CURSOR_API_KEY...");
  try {
    const agent = await Agent.create({
      apiKey,
      model: { id: "composer-2.5" },
      local: { cwd, settingSources: [] },
    });
    await agent[Symbol.asyncDispose]();
  } catch (err) {
    if (err instanceof CursorAgentError) {
      throw new Error(`CURSOR_API_KEY invalid: ${err.message}`);
    }
    throw err;
  }
  core.info("CURSOR_API_KEY: ok");

  core.info("validating GITHUB_TOKEN...");
  const octokit = github.getOctokit(token);
  const { owner, repo } = github.context.repo;

  try {
    await octokit.rest.users.getAuthenticated();
  } catch {
    throw new Error("GITHUB_TOKEN authentication failed");
  }

  const { data: repoData } = await octokit.rest.repos.get({ owner, repo }).catch(() => {
    throw new Error(`GITHUB_TOKEN cannot access ${owner}/${repo}`);
  });
  if (!repoData.permissions?.push) {
    throw new Error("GITHUB_TOKEN lacks contents: write (push permission)");
  }
  if (!repoData.permissions?.pull) {
    throw new Error("GITHUB_TOKEN lacks pull-requests: write (pull permission)");
  }

  if (mode === "fix") {
    try {
      await octokit.rest.actions.listWorkflowRunsForRepo({ owner, repo, per_page: 1 });
    } catch {
      throw new Error("GITHUB_TOKEN lacks actions: read permission");
    }
  }

  const meta = await octokit.request("GET /user");
  const scopes = String(meta.headers["x-oauth-scopes"] ?? "")
    .split(",")
    .map((s) => s.trim())
    .filter(Boolean);
  if (scopes.length > 0 && !scopes.includes("workflow")) {
    throw new Error(
      "GITHUB_TOKEN missing workflow scope (required to push .github/workflows/*)",
    );
  }

  core.info("GITHUB_TOKEN: ok");
}

async function runAgent(
  cwd: string,
  prompt: string,
  apiKey: string,
): Promise<string> {
  core.info("starting Cursor agent...");
  const agent = await Agent.create({
    apiKey,
    model: { id: "composer-2.5" },
    local: { cwd, settingSources: [] },
  });
  try {
    const run = await agent.send(prompt);
    core.info(`agent run started: agentId=${agent.agentId}, runId=${run.id}`);

    const logger = new AgentStreamLogger();
    for await (const event of run.stream()) {
      logger.log(event);
    }
    logger.flush();

    const result = await run.wait();
    if (result.status === "error") {
      throw new Error(`Agent run failed: ${result.id}`);
    }
    core.info(
      `agent finished: status=${result.status}, id=${result.id}${result.durationMs != null ? `, duration=${Math.round(result.durationMs / 1000)}s` : ""}`,
    );
    return result.result ?? "";
  } catch (err) {
    if (err instanceof CursorAgentError) {
      throw new Error(`Cursor startup failed: ${err.message}`);
    }
    throw err;
  } finally {
    await agent[Symbol.asyncDispose]();
  }
}

async function fetchFailureLogs(token: string, runId: number): Promise<string> {
  core.info(`fetching failure logs for workflow run ${runId}...`);
  const octokit = github.getOctokit(token);
  const { owner, repo } = github.context.repo;
  const jobs = await octokit.rest.actions.listJobsForWorkflowRun({
    owner,
    repo,
    run_id: runId,
  });

  core.info(`found ${jobs.data.jobs.length} job(s) in failed run`);
  const parts: string[] = [];
  for (const job of jobs.data.jobs) {
    core.info(`  job "${job.name}": ${job.conclusion}`);
    parts.push(`Job ${job.name}: ${job.conclusion}`);
    try {
      const logs = await octokit.rest.actions.downloadJobLogsForWorkflowRun({
        owner,
        repo,
        job_id: job.id,
      });
      const text = typeof logs.data === "string" ? logs.data : "";
      parts.push(text.slice(-6000));
    } catch {
      core.warning(`  logs unavailable for job "${job.name}"`);
      parts.push("(logs unavailable)");
    }
  }
  const text = parts.join("\n");
  core.info(`collected ${text.length} chars of failure logs`);
  return text;
}

async function resolveSessionId(token: string, headBranch?: string): Promise<number> {
  if (!headBranch) {
    throw new Error("workflow_run missing head_branch; cannot resolve AgentBuild session");
  }

  const fromBranch = parseSessionFromBranch(headBranch);
  if (fromBranch != null) {
    core.info(`session resolved from branch: ${fromBranch}`);
    return fromBranch;
  }

  const octokit = github.getOctokit(token);
  const { owner, repo } = github.context.repo;
  const prs = await octokit.rest.pulls.list({
    owner,
    repo,
    head: `${owner}:${headBranch}`,
    state: "all",
    per_page: 1,
  });
  const pr = prs.data[0];
  if (pr?.body) {
    const fromBody = parseSessionFromPrBody(pr.body);
    if (fromBody != null) {
      core.info(`session resolved from PR #${pr.number} body: ${fromBody}`);
      return fromBody;
    }
  }

  throw new Error(
    `cannot resolve AgentBuild session from branch "${headBranch}" (expected agentbuild/session-{id}/attempt-{n})`,
  );
}

async function listSessionPullRequests(
  token: string,
  sessionId: number,
): Promise<SessionPr[]> {
  const octokit = github.getOctokit(token);
  const { owner, repo } = github.context.repo;

  const { data } = await octokit.rest.search.issuesAndPullRequests({
    q: `repo:${owner}/${repo} "agentbuild-session:${sessionId}" in:body type:pr`,
    per_page: 100,
  });

  const prs: SessionPr[] = [];
  for (const item of data.items) {
    const { data: prData } = await octokit.rest.pulls.get({
      owner,
      repo,
      pull_number: item.number,
    });
    prs.push({
      number: prData.number,
      attempt:
        parseAttemptFromPrBody(prData.body ?? "") ??
        parseAttemptFromBranch(prData.head.ref) ??
        prData.number,
      branch: prData.head.ref,
    });
  }

  prs.sort((a, b) => a.attempt - b.attempt);
  core.info(`session ${sessionId}: ${prs.length} associated PR(s)`);
  return prs;
}

async function getLatestFailedBuildRunId(
  token: string,
  branch: string,
): Promise<number | null> {
  const octokit = github.getOctokit(token);
  const { owner, repo } = github.context.repo;
  const runs = await octokit.rest.actions.listWorkflowRunsForRepo({
    owner,
    repo,
    branch,
    status: "completed",
    per_page: 30,
  });

  const failed = runs.data.workflow_runs.find(
    (run) => run.name === BUILD_WORKFLOW_NAME && run.conclusion === "failure",
  );
  return failed?.id ?? null;
}

async function collectSessionFailureHistory(
  token: string,
  sessionId: number,
  currentRunId?: number,
  currentHeadBranch?: string,
): Promise<string> {
  let prs = await listSessionPullRequests(token, sessionId);
  if (prs.length === 0 && currentHeadBranch) {
    const attempt = parseAttemptFromBranch(currentHeadBranch) ?? 1;
    core.info(
      `session ${sessionId}: no indexed PRs yet; using current branch ${currentHeadBranch}`,
    );
    prs = [{ number: 0, attempt, branch: currentHeadBranch }];
  }
  if (prs.length === 0 && !currentRunId) return "";

  const sections: string[] = [];
  const seenRunIds = new Set<number>();
  let totalChars = 0;

  for (const pr of prs) {
    if (!pr.branch) continue;

    let runId: number | null = null;
    if (currentHeadBranch && pr.branch === currentHeadBranch && currentRunId) {
      runId = currentRunId;
    } else {
      runId = await getLatestFailedBuildRunId(token, pr.branch);
    }
    if (!runId || seenRunIds.has(runId)) continue;
    seenRunIds.add(runId);

    const logs = await fetchFailureLogs(token, runId);
    const budget = Math.min(
      SESSION_LOG_PER_ATTEMPT,
      SESSION_LOG_TOTAL - totalChars,
    );
    if (budget <= 0) {
      sections.push(
        `### 尝试 ${pr.attempt}（PR #${pr.number}，分支 \`${pr.branch}\`）\n(日志已截断，超出会话总长度限制)`,
      );
      break;
    }

    const clipped = truncate(logs, budget);
    totalChars += clipped.length;
    sections.push(
      `### 尝试 ${pr.attempt}（PR #${pr.number}，分支 \`${pr.branch}\`）\n${clipped}`,
    );
  }

  if (currentRunId && !seenRunIds.has(currentRunId)) {
    const logs = await fetchFailureLogs(token, currentRunId);
    const budget = Math.min(
      SESSION_LOG_PER_ATTEMPT,
      SESSION_LOG_TOTAL - totalChars,
    );
    if (budget > 0) {
      sections.push(
        `### 当前失败（workflow run ${currentRunId}）\n${truncate(logs, budget)}`,
      );
    }
  }

  if (sections.length === 0) return "";

  const nextAttempt =
    prs.length > 0 ? Math.max(...prs.map((pr) => pr.attempt)) + 1 : 1;
  return [
    `AgentBuild 会话 \`${sessionId}\`，即将进行第 ${nextAttempt} 次尝试。`,
    `以下为本会话各次失败 PR 的 CI 日志（共 ${sections.length} 条），请参考并避免重复相同错误：`,
    "",
    ...sections,
  ].join("\n\n");
}

function buildFixPrompt(sessionId: number, attempt: number, history: string): string {
  const header = [
    FIX_PROMPT_PREFIX,
    "",
    `会话 ID：\`${sessionId}\`（同一次手动触发的 AgentBuild 共享此 ID；并发的手动触发会有不同 ID）`,
    `当前为第 ${attempt} 次尝试。`,
  ].join("\n");

  if (!history.trim()) {
    return `${header}\n\n日志：`;
  }
  return `${header}\n\n## 本回合历次失败参考\n\n${history}\n\n## 当前需修复的失败日志\n\n见上文最后一次尝试。`;
}

async function commitPr(
  cwd: string,
  token: string,
  branch: string,
  title: string,
  body: string,
): Promise<string> {
  core.info(`creating PR: branch=${branch}, title="${title}"`);
  core.info(`git cwd: ${cwd}`);

  let lastGitLine = "";
  const logGit = (line: Buffer) => {
    const text = line.toString().trimEnd();
    if (!text || text === lastGitLine) return;
    lastGitLine = text;
    core.info(text);
  };
  await exec("git", ["config", "user.name", "github-actions[bot]"], { cwd });
  await exec(
    "git",
    ["config", "user.email", "41898282+github-actions[bot]@users.noreply.github.com"],
    { cwd },
  );
  core.info(`git checkout -b ${branch}`);
  await exec("git", ["checkout", "-b", branch], { cwd, listeners: { stdout: logGit } });
  core.info("git add -A");
  await exec("git", ["add", "-A"], { cwd });
  core.info(`git commit -m "${title}"`);
  await exec("git", ["commit", "-m", title], {
    cwd,
    listeners: { stdout: logGit, stderr: logGit },
  });
  core.info(`git push --force origin ${branch}`);
  try {
    await exec("git", ["push", "--force", "origin", branch], {
      cwd,
      listeners: { stdout: logGit, stderr: logGit },
    });
  } catch {
    throw new Error(
      "git push failed: pushing new .github/workflows/* requires a PAT with " +
        "the workflow scope — replace GITHUB_TOKEN with such a PAT in your workflow env.",
    );
  }

  const octokit = github.getOctokit(token);
  const { owner, repo } = github.context.repo;
  const base =
    github.context.payload?.repository?.default_branch ??
    github.context.ref?.replace("refs/heads/", "") ??
    "main";

  core.info(`opening PR: ${owner}/${repo} ${branch} -> ${base}`);
  const pr = await octokit.rest.pulls.create({
    owner,
    repo,
    title,
    head: branch,
    base,
    body,
  });
  core.info(`PR created: ${pr.data.html_url}`);
  return pr.data.html_url;
}

function resolveMode(input: Mode, cwd: string): "bootstrap" | "fix" {
  if (input === "bootstrap" || input === "fix") {
    core.info(`mode resolved from input: ${input}`);
    return input;
  }
  const hasBuild = existsSync(join(cwd, BUILD_WORKFLOW));
  const failed =
    github.context.eventName === "workflow_run" &&
    github.context.payload.workflow_run?.conclusion === "failure";
  core.info(
    `auto mode: hasBuild=${hasBuild}, event=${github.context.eventName}, failed=${failed}`,
  );
  if (!hasBuild) return "bootstrap";
  if (failed) return "fix";
  return "bootstrap";
}

async function run(): Promise<void> {
  const mode = resolveMode(
    (core.getInput("mode") || "auto") as Mode,
    process.env.GITHUB_WORKSPACE || ".",
  );
  const cwd = process.env.GITHUB_WORKSPACE || process.cwd();
  const apiKey = process.env.CURSOR_API_KEY || "";
  const token = process.env.GITHUB_TOKEN || "";

  core.info(`mode: ${mode}`);
  core.info(`workspace: ${cwd}`);
  core.info(`process.cwd: ${process.cwd()}`);
  core.info(`event: ${github.context.eventName}`);
  core.info(`repo: ${github.context.repo.owner}/${github.context.repo.repo}`);
  core.info(`CURSOR_API_KEY: ${apiKey ? "set" : "not set"}`);
  if (token) {
    core.info(
      `GITHUB_TOKEN: set (${token.slice(0, 4)}...${token.slice(-4)} len=${token.length})`,
    );
  } else {
    core.info("GITHUB_TOKEN: not set");
  }

  await validateSetup(mode, cwd, apiKey, token);

  if (mode === "bootstrap") {
    core.info("scanning project with AI and generating build workflow...");
    await runAgent(cwd, BOOTSTRAP_PROMPT, apiKey);

    const workflowPath = join(cwd, BUILD_WORKFLOW);
    if (!existsSync(workflowPath)) {
      core.setFailed(`${BUILD_WORKFLOW} was not created by agent`);
      return;
    }
    core.info(`workflow ready: ${workflowPath}`);

    const sessionId = github.context.runId;
    const attempt = 1;
    const url = await commitPr(
      cwd,
      token,
      sessionBranch(sessionId, attempt),
      "chore(ci): add build workflow",
      sessionPrBody(sessionId, attempt),
    );
    core.setOutput("session-id", String(sessionId));
    core.setOutput("pr-url", url);
    core.info("bootstrap finished");
    return;
  }

  const workflowRun = github.context.payload.workflow_run;
  const runId = workflowRun?.id;
  const headBranch = workflowRun?.head_branch ?? undefined;
  if (!runId) {
    core.warning("no workflow_run.id in payload; agent will run without logs");
  }

  const sessionId = await resolveSessionId(token, headBranch);
  const sessionPrs = await listSessionPullRequests(token, sessionId);
  const attempt =
    sessionPrs.length > 0
      ? Math.max(...sessionPrs.map((pr) => pr.attempt)) + 1
      : 1;
  core.info(`session=${sessionId}, attempt=${attempt}, prior PRs=${sessionPrs.length}`);

  const history = await collectSessionFailureHistory(
    token,
    sessionId,
    runId,
    headBranch,
  );
  const prompt = buildFixPrompt(sessionId, attempt, history);

  await runAgent(cwd, prompt, apiKey);

  const url = await commitPr(
    cwd,
    token,
    sessionBranch(sessionId, attempt),
    "fix(ci): repair build workflow",
    sessionPrBody(sessionId, attempt),
  );
  core.setOutput("session-id", String(sessionId));
  core.setOutput("pr-url", url);
  core.info("fix finished");
}

run().catch((err: unknown) => {
  core.setFailed(err instanceof Error ? err.message : String(err));
});
